name: Cypress Tests

env:
      GOOGLE_EMAIL: ${{ secrets.GOOGLE_EMAIL }}
      GOOGLE_CLIENTID: ${{ secrets.GOOGLE_CLIENTID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on: [push]

jobs:
  # cypress-run:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     # Install NPM dependencies, cache them correctly
  #     # and run all Cypress tests
  #     - name: Cypress run
  #       uses: cypress-io/github-action@v4
  #       with:
  #         build: npm install
  #         start: npm run cypress:run --headed --browser chrome --spec 'cypress/e2e/yll/**' --record --key b2d95fbf-4fe7-42cc-8a13-f6828ab975f1

  # firefox:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: cypress-io/github-action@v4
  #       with:
  #         # browser: firefox
  #         build: npm install
  #         start: npm run cypress:run --headed --browser firefox --spec 'cypress/e2e/yll/**'

  # edge:
  #   runs-on: windows-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: cypress-io/github-action@v4
  #       with:
  #         # browser: edge
  #         build: npm install
  #         start: npm run cypress:run --headed --browser edge --spec 'cypress/e2e/yll/**'

  # chrome:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: cypress-io/github-action@v4
  #       with:
  #         # browser: chrome
  #         # headed: true
  #         build: npm install
  #         start: npm run cypress:run --headed --browser chrome --spec 'cypress/e2e/yll/**'

  electron:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v4
        with:
          browser: electron
          spec: 'cypress/e2e/yll/**'
          headed: true
          build: npm install