name: Cypress Tests

env:
  GOOGLE_EMAIL: ${{ secrets.GOOGLE_EMAIL }}
  GOOGLE_CLIENTID: ${{ secrets.GOOGLE_CLIENTID }}
  GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
  GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on: [push, workflow_dispatch]

jobs:
  firefox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v4
        with:
          browser: firefox
          spec: 'cypress/e2e/yll/**'
          headed: true
          build: npm install

  edge:
    # force jobs to run sequentially. 
    needs: firefox 
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v4
        with:
          browser: edge
          spec: 'cypress/e2e/yll/**'
          headed: true
          build: npm install

  chrome:
    # force jobs to run sequentially. 
    needs: edge 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v4
        with:
          browser: chrome
          spec: 'cypress/e2e/yll/**'
          headed: true
          build: npm install

  electron:
    # force jobs to run sequentially. 
    needs: chrome
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v4
        with:
          browser: electron
          spec: 'cypress/e2e/yll/**'
          headed: true
          build: npm install